default:
  app_name: Jinglr
  fb_app_id: 
  fb_admins: 
  fb_graph_url: https://graph.facebook.com/oauth/access_token
  email_general: "info@jinglr.com"
  email_abuse: "abuse@jinglr.com"
  email_press: "orlando@jinglr.com"
  email_webmaster: "webmaster@jinglr.com"
  email_admin: "orlando@jinglr.com"
  comment_maxlength: 200
  jingle_desc_maxlength: 200
  track_mixer_max: 2
  
development:
  domain: jinglr.dev
  url: http://jinglr.dev
  fb_oath_callback_url: "http://jinglr.dev/oauth/callback?provider=facebook"
  fb_secret: 
production:
  domain: jinglr.com
  url: http://jinglr.com
  fb_oath_callback_url: "http://jinglr.com/oauth/callback?provider=facebook"
  fb_secret: 
